events{
    worker_connections 1024;
}

http{
    server{
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://gusto-eats-frontend:3000;
        }

        location /api {
            proxy_pass http://gusto-eats-backend:8000;
        }

        location /api/docs{
            proxy_pass http://gusto-eats-backend:8000/;
        }
    }
}