# Generated by Django 5.0.1 on 2024-07-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_order_user_alter_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='email',
            new_name='for_contact',
        ),
    ]
