# Generated by Django 5.0.1 on 2024-07-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_email_feedback_for_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='for_contact',
            field=models.CharField(max_length=255),
        ),
    ]
