name: Reload Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Reload Docker Containers on Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Deploy to AWS
      #   run: |
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
      #     chmod 600 ~/ssh_key

      #     ssh -o StrictHostKeyChecking=no -i "~/ssh_key" ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
      #       cd ~/rental-yards

      #       # ENVIRONMENT variablesni saqlash
      #       echo "${{ secrets.ENV_FILE }}" | tr ' ' '\n' > .env

      #       # Git pull qilish
      #       git pull origin frontend

      #       # Ortiqcha fayllarni o'chirish
      #       rm -rf frontend backend .github

      #       # Docker imagelarni pull qilish
      #       sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.FRONTEND_IMAGE_NAME }}:latest
      #       sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.BACKEND_IMAGE_NAME }}:latest

      #       # Docker frontendni qayta ishga tushirish
      #       sudo docker compose stop frontend
      #       sudo docker compose rm -f frontend
      #       sudo docker compose up -d frontend

      #       # Keraksiz Docker image va containerlarni tozalash
      #       sudo docker image prune -f
      #       sudo docker container prune -f
      #     EOF
